const DEFAULT_CORNER_RADIUS = 4;
const DEFAULT_STROKE_COLOR = '#000000';
const DEFAULT_STROKE_WIDTH = 1;
const DEFAULT_STROKE_STYLE: number[] = [];
const DEFAULT_FILL_BACKGROUND = '#ffffff';
const DEFAULT_FONT_FAMILY = 'Balsamiq Sans, Comic Sans MS, cursive';
const DEFAULT_FONT_SIZE = 16;
const DEFAULT_FILL_TEXT = '#000000';
const DEFAULT_PADDING = 10;
const DEFAULT_LINE_HEIGHT = 1.25;
const DEFAULT_FILL_TEXT_INPUT = '#8c8c8c';
const DEFAULT_FONT_SIZE_INPUT = 15;
const DEFAULT_TEXT_WIDTH = 165;
const DEFAULT_TEXT_HEIGHT = 38;
const DEFAULT_FONT_VARIANT = 'normal';
const DEFAULT_FONT_STYLE = 'normal';
const DEFAULT_TEXT_DECORATION = 'none';

export interface DefaultStyleShape {
  DEFAULT_CORNER_RADIUS: number;
  DEFAULT_STROKE_COLOR: string;
  DEFAULT_STROKE_WIDTH: number;
  DEFAULT_FILL_BACKGROUND: string;
  DEFAULT_FONT_FAMILY: string;
  DEFAULT_FONT_SIZE: number;
  DEFAULT_FILL_TEXT: string;
  DEFAULT_PADDING: number;
  DEFAULT_LINE_HEIGHT: number;
  DEFAULT_TEXT_WIDTH: number;
  DEFAULT_TEXT_HEIGHT: number;
  DEFAULT_STROKE_STYLE: number[];
  DEFAULT_FONT_VARIANT: string;
  DEFAULT_FONT_STYLE: string;
  DEFAULT_TEXT_DECORATION: string;
}

export const BASIC_SHAPE: DefaultStyleShape = {
  DEFAULT_CORNER_RADIUS,
  DEFAULT_STROKE_COLOR,
  DEFAULT_STROKE_WIDTH,
  DEFAULT_FILL_BACKGROUND,
  DEFAULT_FONT_FAMILY,
  DEFAULT_FONT_SIZE,
  DEFAULT_FILL_TEXT,
  DEFAULT_PADDING,
  DEFAULT_LINE_HEIGHT,
  DEFAULT_TEXT_WIDTH,
  DEFAULT_TEXT_HEIGHT,
  DEFAULT_STROKE_STYLE,
  DEFAULT_FONT_VARIANT,
  DEFAULT_FONT_STYLE,
  DEFAULT_TEXT_DECORATION,
};

export const INPUT_SHAPE: DefaultStyleShape = {
  DEFAULT_CORNER_RADIUS,
  DEFAULT_STROKE_COLOR,
  DEFAULT_STROKE_WIDTH,
  DEFAULT_FILL_BACKGROUND,
  DEFAULT_FONT_FAMILY,
  DEFAULT_FONT_SIZE: DEFAULT_FONT_SIZE_INPUT,
  DEFAULT_FILL_TEXT: DEFAULT_FILL_TEXT_INPUT,
  DEFAULT_PADDING,
  DEFAULT_LINE_HEIGHT,
  DEFAULT_TEXT_WIDTH,
  DEFAULT_TEXT_HEIGHT,
  DEFAULT_STROKE_STYLE,
  DEFAULT_FONT_VARIANT,
  DEFAULT_FONT_STYLE,
  DEFAULT_TEXT_DECORATION,
};

//! maybe a function to calc max height base on the text
export const POSTIT_SHAPE: DefaultStyleShape = {
  DEFAULT_CORNER_RADIUS,
  DEFAULT_STROKE_COLOR,
  DEFAULT_STROKE_WIDTH,
  DEFAULT_FILL_BACKGROUND: '#FFFF99',
  DEFAULT_FONT_FAMILY,
  DEFAULT_FONT_SIZE: DEFAULT_FONT_SIZE_INPUT,
  DEFAULT_FILL_TEXT: '#000000',
  DEFAULT_PADDING,
  DEFAULT_LINE_HEIGHT,
  DEFAULT_TEXT_WIDTH,
  DEFAULT_TEXT_HEIGHT,
  DEFAULT_STROKE_STYLE,
  DEFAULT_FONT_VARIANT,
  DEFAULT_FONT_STYLE,
  DEFAULT_TEXT_DECORATION,
};

interface FontValues {
  heading1: number;
  heading2: number;
  heading3: number;
  normaltext: number;
  smalltext: number;
  paragraph: number;
  link: number;
}

export const FONT_SIZE_VALUES: FontValues = {
  heading1: 28,
  heading2: 24,
  heading3: 18,
  normaltext: 18,
  smalltext: 14,
  paragraph: 14,
  link: 20,
};
