storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@lemoncode/*':
    access: $all
    publish: $all
    unpublish: $all
  '**':
    access: $all
    publish: $all
    proxy: npmjs

server:
  keepAliveTimeout: 60

log: { type: stdout, format: pretty, level: warn }
