name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  cd:
    environment:
      name: Production
      url: https://quickmock.net
    runs-on: ubuntu-latest
    name: Deploy Quickmock
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_FIELD_0DCD26F03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/dist"
          skip_app_build: true
          skip_api_build: true
        env:
          NODE_VERSION: 20.17.0
